# Generated by Django 4.1.7 on 2023-05-20 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=30, verbose_name='email')),
                ('dob', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('extype', models.IntegerField(choices=[(70, '0-30 minutes         '), (250, '30-90 minutes        '), (600, 'More than 90 minutes ')], null=True)),
                ('gender', models.IntegerField(choices=[(5, 'Male                 '), (-161, 'Female               ')], null=True)),
                ('veg', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='hcondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='nutpar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='recipe1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DishName', models.CharField(max_length=100)),
                ('MealType', models.CharField(max_length=100)),
                ('Calories', models.IntegerField()),
                ('Protein', models.IntegerField()),
                ('Carbohydrates', models.IntegerField()),
                ('Fat', models.IntegerField()),
                ('Sugar', models.IntegerField()),
                ('DietaryFiber', models.IntegerField()),
                ('VitaminA', models.IntegerField()),
                ('VitaminC', models.IntegerField()),
                ('Calcium', models.IntegerField()),
                ('Iron', models.IntegerField()),
                ('Potassium', models.IntegerField()),
                ('GlutenFree', models.BooleanField()),
                ('Vegetarian', models.BooleanField()),
                ('Vegan', models.BooleanField()),
                ('DiabeticFriendly', models.BooleanField()),
                ('LactoseFree', models.BooleanField()),
                ('NutFree', models.BooleanField()),
                ('LowCarb', models.BooleanField()),
                ('LowFat', models.BooleanField()),
                ('HighFiber', models.BooleanField()),
                ('LowSodium', models.BooleanField()),
                ('DairyFree', models.BooleanField()),
                ('EggFree', models.BooleanField()),
                ('SoyFree', models.BooleanField()),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='suser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcon', models.ManyToManyField(to='main.hcondition')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rtype', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], max_length=10, null=True)),
                ('veg', models.BooleanField(default=False)),
                ('Detail', models.CharField(max_length=1000)),
                ('energy', models.IntegerField(null=True)),
                ('hcon', models.ManyToManyField(to='main.hcondition')),
                ('npr', models.ManyToManyField(to='main.nutpar')),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suserid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.suser')),
            ],
        ),
    ]
